### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by dan-muller** [secret-traitor/secret-traitor#29]
see:
https://github.com/secret-traitor/secret-traitor/runs/1631579006?check_suite_focus=true

The `Deploy to prod` stage in ci is failing with the message 
``` 
6/42 | 9:02:05 PM | CREATE_FAILED        | Custom::CDKBucketDeployment   | WebsiteBucketDeployment/CustomResource/Default (WebsiteBucketDeploymentCustomResource1BCCE8A6) Failed to create resource. Command '['python3', '/var/task/aws', 's3', 'sync', '--delete', '/tmp/tmpx4ubkuu1/contents', 's3://secrettraitorstack-websitebucket75c24d94-e0grmveo4wx8/']' returned non-zero exit status 1.
	new CustomResource (/home/runner/work/secret-traitor/secret-traitor/infrastucture/node_modules/@aws-cdk/core/lib/custom-resource.ts:119:21)
	\_ new BucketDeployment (/home/runner/work/secret-traitor/secret-traitor/infrastucture/node_modules/@aws-cdk/aws-s3-deployment/lib/bucket-deployment.ts:219:5)
	\_ new SecretTraitorStack (/home/runner/work/secret-traitor/secret-traitor/infrastucture/lib/secret-traitor-stack.ts:74:41)
	\_ Object.<anonymous> (/home/runner/work/secret-traitor/secret-traitor/infrastucture/lib/index.ts:6:1)
	\_ Module._compile (internal/modules/cjs/loader.js:1063:30)
	\_ Module.m._compile (/home/runner/work/secret-traitor/secret-traitor/infrastucture/node_modules/ts-node/src/index.ts:858:23)
	\_ Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
	\_ Object.require.extensions.<computed> [as .ts] (/home/runner/work/secret-traitor/secret-traitor/infrastucture/node_modules/ts-node/src/index.ts:861:12)
	\_ Module.load (internal/modules/cjs/loader.js:928:32)
	\_ Function.Module._load (internal/modules/cjs/loader.js:769:14)
	\_ Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
	\_ main (/home/runner/work/secret-traitor/secret-traitor/infrastucture/node_modules/ts-node/src/bin.ts:227:14)
	\_ Object.<anonymous> (/home/runner/work/secret-traitor/secret-traitor/infrastucture/node_modules/ts-node/src/bin.ts:513:3)
	\_ Module._compile (internal/modules/cjs/loader.js:1063:30)
	\_ Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
	\_ Module.load (internal/modules/cjs/loader.js:928:32)
	\_ Function.Module._load (internal/modules/cjs/loader.js:769:14)
	\_ Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
	\_ /usr/local/lib/node_modules/npm/node_modules/libnpx/index.js:268:14
```

I guess its not able to delete the bucket before redeploying it?

**Comment by dan-muller** [comment]
@douglasnaphas does this bring up any thoughts for you?

**Comment by douglasnaphas** [comment]
Our [logs](https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/$252Faws$252Flambda$252FSecretTraitorStack-CustomCDKBucketDeployment8693BB-XJO2G9G1OJIR/log-events/2020$252F12$252F31$252F$255B$2524LATEST$255D2db0cf4ab12141649b2345afa6286b1d) say:

> [INFO]	2020-12-31T21:19:19.916Z	3c6d2b87-e19f-4e4f-b143-62574ee9fdee	| aws s3 sync --delete /tmp/tmp10siphxw/contents s3://secrettraitorstack-websitebucket75c24d94-e0grmveo4wx8/
> fatal error: An error occurred (NoSuchBucket) when calling the ListObjectsV2 operation: The specified bucket does not exist

I'm not sure why the bucket s3://secrettraitorstack-websitebucket75c24d94-e0grmveo4wx8/ doesn't exist, but `aws s3api list-buckets` confirms that it doesn't.

**Comment by douglasnaphas** [comment]
Pretty strange that the _Deploy to test_ step successfully deploys to the test account, but the _Deploy to prod_ test fails to deploy to the prod account.

That does perhaps give us another lead, as we can go and see if, for example, the WebsiteBucket that's missing from the prod account is present in the test account.

**Comment by douglasnaphas** [comment]
It could be because the bucket in the test account has the same bucket name as the bucket we are attempting to create in the prod account (s3://secrettraitorstack-websitebucket75c24d94-e0grmveo4wx8), and S3 bucket names have to be globally unique.

If that's the problem, which I'm going to confirm by looking for a bucket named s3://secrettraitorstack-websitebucket75c24d94-e0grmveo4wx8 in the test account, then we could fix the problem by parameterizing the stack name with a CLI input.

The Unique IDs and Logical IDs sections of [this doc](https://docs.aws.amazon.com/cdk/latest/guide/identifiers.html) on CDK identifiers is relevant.

**Update**: The test bucket has a different URI (s3://secrettraitorstack-websitebucket75c24d94-1xen05cst0zcw), exists, and has the expected contents. That seems to rule out the theories that we're in the wrong directory, or that there's an S3 bucket naming conflict between the test and prod accounts.

**Comment by douglasnaphas** [comment]
Maybe it's because of this from the CDK identifiers docs I linked in my previous comment:

> **Logical ID stability**
>
> Avoid changing the logical ID of a resource between deployments. Since AWS CloudFormation identifies resources by their logical ID, if you change the logical ID of a resource, AWS CloudFormation deletes the existing resource, and then creates a new resource with the new logical ID.

I wonder if when we made [this change](https://github.com/secret-traitor/secret-traitor/commit/b8fba04ed1350e2fa14b244d9f153789e618b27b#diff-8fcd33a464bd99215c98c944651d68421d8fd6ecd0c76c56d31e34ca6412f6faL48) to the logical ID of the experimental [S3 Deployment](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-s3-deployment-readme.html) resource, it triggered a deletion of the S3 Deployment resource, and that, by some bug in the S3 Deployment code, led to a deletion of the bucket it was supposed to deploy to. Then the target bucket would not have been there when the new S3 Deployment resource tried to deploy to it.

We can _hopefully_ use [AWS CloudTrail](https://aws.amazon.com/cloudtrail/) to pinpoint when the WebsiteBucket was deleted, or, better yet, maybe we can see it from the logs and/or CloudFormation events from when the [build](https://github.com/secret-traitor/secret-traitor/actions/runs/455088226) following the S3 Deployment rename.

**Comment by douglasnaphas** [comment]
CloudTrail does have some info.

If you run `aws --region=us-east-1 cloudtrail lookup-events --lookup-attributes AttributeKey=EventName,AttributeValue=DeleteBucket`, it looks like the bucket was manually deleted. You can run that from a local shell with your AWS profile targeting the prod account, or you can use a new service [CloudShell](https://aws.amazon.com/cloudshell/) which gives you a free shell in your browser that is authenticated with whatever credentials you used to log in to the AWS web console. So you could log in to the console for the Secret Traitor prod account, go to us-east-1, and search for CloudShell, and start a session, and run that command to see the DeleteBucket events.

Not sure why our setup can't recover from a resource being manually deleted.

**Comment by douglasnaphas** [comment]
I can see from [drift detection](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/detect-drift-stack.html) that our CloudFormation stack has "drifted." The details of our drift are that the missing bucket has been deleted, as we'd expect based on my previous comment.

<img width="1654" alt="Screen Shot 2021-01-01 at 12 07 14 PM" src="https://user-images.githubusercontent.com/5433410/103443238-3a477b80-4c2b-11eb-923f-a84a15b36844.png">

----

<img width="1676" alt="Screen Shot 2021-01-01 at 12 16 42 PM" src="https://user-images.githubusercontent.com/5433410/103443245-3e739900-4c2b-11eb-9612-4f77c3c107d4.png">

I bet we can resolve the problem by manually creating the bucket. We may then need to [import it](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import-existing-stack.html) back into our stack in the console. But I'll run the build in GitHub Actions again after re-creating the bucket manually to see if that fixes it.

If this is indeed the problem, we can protect against it in the future by having our build check for drift before deploying, and fail if there is any drift. We could also implement [automatic drift remediation](https://aws.amazon.com/blogs/mt/implement-automatic-drift-remediation-for-aws-cloudformation-using-amazon-cloudwatch-and-aws-lambda/).

**Comment by douglasnaphas** [comment]
Bucket re-created manually...

<img width="1405" alt="Screen Shot 2021-01-01 at 1 08 34 PM" src="https://user-images.githubusercontent.com/5433410/103443997-7cc08680-4c32-11eb-9bad-bd47eff5d18c.png">

**Comment by douglasnaphas** [comment]
Build is green again after manual bucket re-creation. I did not have to re-import the bucket. That makes sense, because CloudFormation identifies the resource using its physical ID/ARN, so if I create a bucket with the expected name/physical ID, CloudFormation would have no way to know that it wasn't created by CloudFormation.

Closing.
